apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: app
  namespace: lanchonete
type: Opaque
data:
    connection-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvbGFuY2hvbmV0ZT9zY2hlbWE9cHVibGljCg== #postgresql://postgres:postgres@postgres:5432/lanchonete?schema=public
