version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: tooling/docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 7000
    ports:
      - 7000:7000
    command: npm run start
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
    ports:
      - 5432:5432
    volumes:
      - ./tooling/postgres/init_db.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    default:
        name: lanchonete-network
